import { AgendaItem, CommitteeMember } from '../models/agenda.models';

/**
 * Builds the standard Toastmasters-style agenda template, seeded with
 * committee names where roles are known. `nextId` is called once per
 * item to obtain ids, mirroring the caller's own id counter.
 */
export function defaultAgenda(cmt: CommitteeMember[], nextId: () => number): AgendaItem[] {
  const president = cmt.find((m) => m.roleId === 'president');
  const secretary = cmt.find((m) => m.roleId === 'secretary');
  const vpEducation = cmt.find((m) => m.roleId === 'vpEducation');

  return [
    {
      id: nextId(),
      type: 'row',
      title: 'Call to order',
      person: secretary?.name || '',
      roleId: 'secretary',
      roleVisible: true,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Welcome',
      person: president?.name || '',
      roleId: 'president',
      roleVisible: true,
      customRoleLabel: null,
      duration: 3,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Meeting Leader (Evening Chairman)',
      person: '',
      roleId: 'toastmaster',
      roleVisible: false,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Programme Information',
      person: vpEducation?.name || '',
      roleId: 'vpEducation',
      roleVisible: true,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Timekeeper (explain role)',
      person: '',
      roleId: 'timer',
      roleVisible: false,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Grammarian (explain role)',
      person: '',
      roleId: 'grammarian',
      roleVisible: false,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Filler Word Counter (explain role)',
      person: '',
      roleId: 'ahCounter',
      roleVisible: false,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Introductions',
      person: '',
      roleId: 'toastmaster',
      roleVisible: true,
      customRoleLabel: null,
      duration: 16,
    },
    {
      id: nextId(),
      type: 'dual',
      durationA: 10,
      items: [
        { title: 'Impromptu Session', person: '', roleId: 'impromptuMaster', roleVisible: true, customRoleLabel: null },
        { title: 'Prepared Speaking Session', person: '', roleId: 'toastmaster', roleVisible: true, customRoleLabel: null },
      ],
    },
    {
      id: nextId(),
      type: 'speakers',
    },
    {
      id: nextId(),
      type: 'recess',
      title: 'Recess',
      duration: 15,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Call to order',
      person: secretary?.name || '',
      roleId: 'secretary',
      roleVisible: true,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Evaluation Session',
      person: '',
      roleId: 'toastmaster',
      roleVisible: true,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'evaluators',
    },
    {
      id: nextId(),
      type: 'row',
      title: "Timekeeper's Report",
      person: '',
      roleId: 'timer',
      roleVisible: false,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: "Grammarian's Report",
      person: '',
      roleId: 'grammarian',
      roleVisible: false,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: "Filler Word Counter's Report",
      person: '',
      roleId: 'ahCounter',
      roleVisible: false,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Meeting Evaluator',
      person: '',
      roleId: 'generalEvaluator',
      roleVisible: false,
      customRoleLabel: null,
      duration: 5,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Educational',
      person: '',
      roleId: 'toastmaster',
      roleVisible: false,
      customRoleLabel: null,
      duration: 10,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Planning for Next Meeting',
      person: vpEducation?.name || '',
      roleId: 'vpEducation',
      roleVisible: true,
      customRoleLabel: null,
      duration: 2,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Awards/Open Discussion',
      person: president?.name || '',
      roleId: 'president',
      roleVisible: true,
      customRoleLabel: null,
      duration: 4,
    },
    {
      id: nextId(),
      type: 'row',
      title: 'Meeting Adjourned',
      person: president?.name || '',
      roleId: 'president',
      roleVisible: true,
      customRoleLabel: null,
      duration: 0,
    },
  ] as AgendaItem[];
}
